


stereo_tracker.8Xp: stereo_tracker.bin
	python3 ../LINK/wrap_minified_asm.py -i stereo_tracker.bin -o stereo_tracker.8Xp -n ASTRACK

stereo_tracker.bin: stereo_tracker.z80
	../assemblers/z80asm-1.8/z80asm -i stereo_tracker.z80 -o stereo_tracker.bin
